apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'custom-jenkins:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'jenkins:2'
  source:
    type: Git
    git:
      uri: 'https://github.com/sixpac009-learning/jenkins-s2i.git'
      ref: master
  triggers:
    - type: ConfigChange
  runPolicy: Serial
