apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
  namespace: jenkins
spec:
  output:
    to:
      kind: ImageStreamTag
      name: custom-jenkins:latest
  source:
    git:
      ref: master
      uri: https://github.com/sixpac009-learning/jenkins-s2i.git
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:2
        namespace: openshift
      env: []
  triggers:
  - type: ConfigChange
