apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- serviceaccount.yaml
- rolebinding.yaml
- service-jnlp.yaml
- service.yaml
- deployment.yaml
- route.yaml